# Generated by Django 3.1.5 on 2021-05-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.AddField(
            model_name='products',
            name='cat',
            field=models.CharField(choices=[('wedding', 'wedding'), ('brithday', 'brithday'), ('photoshot', 'photoshot'), ('themes', 'themes')], default='wedding', max_length=10),
        ),
    ]
