# Generated by Django 3.1.5 on 2021-06-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210522_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='heroimage',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
