# Generated by Django 3.1.5 on 2021-06-26 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210625_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
