# Generated by Django 3.1.5 on 2021-06-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
