# Generated by Django 3.1.5 on 2021-06-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_products_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
