# Generated by Django 3.1.5 on 2021-06-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210523_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zipcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
