# Generated by Django 3.1.5 on 2021-06-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adderss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(default='user address', max_length=500)),
                ('city', models.CharField(default='enter your own city', max_length=40)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(default='uttarperdesh', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='add',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zipcode',
        ),
    ]
