# Generated by Django 3.1.5 on 2021-06-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210624_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(default='no img', upload_to='img'),
        ),
    ]
